apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: serverless-createpostgresdb-app
  annotations:
    backstage.io/techdocs-ref: dir:.
    aws.com/lambda-function-name: serverless-createpostgresdb-dev-get-create-db
    aws.com/lambda-region: us-east-1
    github.com/project-slug: 'hesitationgames/serverless-createpostgresdb'
  links:
    - title: Serverless framework
      url: https://www.serverless.com/framework/docs
      icon: dashboard
  description: This is a api that creates postgres databases for backstage templates
  tags:
    - backend
    - sls
    - nodejs
spec:
  type: service
  lifecycle: experimental
  owner: user:default/juancarestre
  system: system:default/internal-tools
  consumesApis:
    - serverless-createpostgresdb-api
  providesApis:
    - serverless-createpostgresdb-api

  # https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component


---

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: serverless-createpostgresdb-api
  description: A very basic serverless-createpostgresdb api, This is a api that creates postgres databases for backstage templates
spec:
  type: openapi
  lifecycle: experimental
  owner: user:default/juancarestre
  system: system:default/internal-tools
  definition: |
    openapi: "3.0.1"
    info:
      title: "serverless-createpostgresdb-api"
      description: "This is a api that creates postgres databases for backstage templates"
      version: "V0.0.1"
    servers:
    - url: https://{API_URL}/{API_STAGE}/
      variables:
        API_URL:
          default: y9ggm5si49.execute-api.us-west-2.amazonaws.com
          description: API URL provided by apigateway or custom domain
        API_STAGE:
          default: latest
          description: API stage - Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac arcu id libero lacinia congue. Nulla facilisi. Proin sagittis, velit eu accumsan auctor, quam ex viverra purus, vel tincidunt risus elit nec nunc. Sed sed mauris vitae orci egestas gravida in non ex. Etiam in ante a libero iaculis vulputate. Nulla facilisi. Morbi nec ultrices purus. Fusce dictum consectetur libero, ac laoreet velit sollicitudin sit amet. Sed fringilla ex vitae tortor semper, a varius dolor facilisis. Aliquam vel elit at quam scelerisque hendrerit. Nunc non neque ac nisi consequat bibendum vel eu urna.
    paths:
      /hello-world:
        get:
          summary: "Get hello world"
          description: "Get datetime with a helloworld message"
          responses:
            "200":
              description: "Returns hello world with datetime"
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/greetingsBodyResponse"

          x-amazon-apigateway-integration:
            httpMethod: "POST"
            uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:597701726802:function:serverless-createpostgresdb-{API_STAGE}-get-hello-world/invocations"
            passthroughBehavior: "when_no_match"
            type: "aws_proxy"
        post:
          summary: "Post hello world"
          description: "Post that returns datetime with a helloworld message"
          requestBody:
            $ref: '#/components/requestBodies/greetingsBody'

          responses:
            "200":
              description: "Returns hello world with datetime"
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/greetingsBodyResponse"

          x-amazon-apigateway-integration:
            httpMethod: "POST"
            uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:597701726802:function:serverless-createpostgresdb-{API_STAGE}-post-hello-world/invocations"
            passthroughBehavior: "when_no_match"
            type: "aws_proxy"
    components:
      schemas:
        greetingsBody:
          type: object
          properties:
            greetings:
              type: string
          required: ['greetings']
        greetingsBodyResponse:
          type: object
          properties:
            hello:
              type: string

      requestBodies:
        greetingsBody:
          description: Standard body
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/greetingsBody'
          required: true
