service: serverless-createpostgresdb
configValidationMode: warn
frameworkVersion: '3.2.0'

provider:
  name: aws
  runtime: nodejs18.x
  endpointType: REGIONAL
  apiName: "${self:service}-${self:custom.stage}-api"
  region: us-east-1
  memorySize: 128
  timeout: 10
  stage: ${opt:stage, 'staging'}
  apiGateway:
    request:
      schemas:
        post-hello-model:
          name: PostHelloModel
          schema: ${file(./openapi.yaml):components.schemas.greetingsBody}
          description: "A Model validation for hello"

package:
  individually: true
  patterns:
    - "!*/**"

custom:
  stage: ${opt:stage, 'dev'}
  static_envs:
    prod: prod
    other: staging
  envtype: ${self:custom.static_envs.${opt:stage}, self:custom.static_envs.other}
  documentation: ${file(./openapi.yaml)}

plugins:
  - serverless-openapi-documenter

functions:
  createDatabase:
    handler: app.handler
    name: "${self:service}-${self:custom.stage}-get-create-db"
    package:
      patterns:
        - "app.js"
    events:
      - http:
          path: /create-db/
          method: get
          cors: true
      - http:
          path: /create-db/
          method: post
          cors: true
